a = input('Digite um valor')
print(a, 'é da', type(a))
print(a, 'é um número?', a.isnumeric())
print('só tem espaços?', a.isspace())
print('é alfa-numérico?', a.isalnum())
print('é só letras?', a.isalpha())
print('está em maisculo?', a.isupper())
print('está em minúscolo?', a.islower())
print('está capitalizada?', a.istitle())
